#!/usr/bin/env bash
if [[ -z $(command -v python) ]]; then
  echo "ERR: Python is required!"
  exit 1
fi

if [[ -z $(command -v pipx) ]]; then
  echo "ERR: pipx is required!"
  echo "Install via: pip install pipx"
  exit 1
fi

python -m pipx install json-linter -U > /dev/null
pipx run json-linter ${@}
